/**
 * Account-deletion confirmation email sent before permanently removing a user.
 * Dispatched via the Better Auth `deleteUser` verification hook.
 */

import { sendEmail } from "./send-email";

/**
 * Payload shape supplied by Better Auth's account-deletion hook.
 *
 * @author Maruf Bepary
 */
interface EmailVerificationData {
  user: {
    name: string;
    email: string;
  };
  url: string;
}

/**
 * Sends an account-deletion confirmation email before permanently removing a user.
 * Triggered by the Better Auth account-deletion flow to require explicit user approval.
 * User must click the verification link within 24 hours to confirm deletion; otherwise the request expires.
 *
 * @param user - Account owner's name and email from Better Auth
 * @param url - Deletion-approval URL generated by Better Auth (expires 24h)
 * @throws {ServerError} When Postmark fails to send the email
 * @see sendEmail for underlying Postmark integration
 * @author Maruf Bepary
 */
export async function sendDeleteAccountVerificationEmail({
  user,
  url,
}: EmailVerificationData) {
  await sendEmail({
    to: user.email,
    subject: "Delete your account",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333;">Confirm Account Deletion</h2>
        <p>Hello ${user.name},</p>
        <p>We're sorry to see you go! Please confirm your account deletion by clicking the button below:</p>
        <a href="${url}" style="background-color: #28a745; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block; margin: 16px 0;">Confirm Deletion</a>
        <p>If you don't have an account, please ignore this email.</p>
        <p>This link will expire in 24 hours.</p>
        <p>Best regards,<br>Your App Team</p>
      </div>
    `,
    text: `Hello ${user.name},\n\nWe're sorry to see you go! Please confirm your account deletion by clicking this link: ${url}\n\nIf you don't have an account, please ignore this email.\n\nThis link will expire in 24 hours.\n\nBest regards,\nYour App Team`,
  });
}
