/**
 * Status of a transform run execution.
 * - "pending": Created but not yet started.
 * - "running": Currently executing steps.
 * - "awaiting_review": Paused for manual approval before next step.
 * - "completed": Successfully finished all steps.
 * - "failed": Stopped due to error.
 *
 * @author Maruf Bepary
 */
export type TransformRunStatus =
  | "pending"
  | "running"
  | "awaiting_review"
  | "completed"
  | "failed";

/**
 * Represents an execution instance of a transform agent workflow.
 * Tracks progress through steps, input/output files, and errors.
 * Enables pausing for review and resuming from the current step.
 *
 * @author Maruf Bepary
 */
export type TransformRun = {
  /** Unique identifier for this execution. */
  id: string;

  /** ID of the workflow being executed. */
  agentId: string;

  /** User ID that initiated this run. */
  userId: string;

  /** Current execution status (pending, running, awaiting_review, completed, failed). */
  status: TransformRunStatus;

  /** Index of the current step (null if not started or completed). */
  currentStepIndex: number | null;

  /** Whether this is a preview run without persisting results. */
  dryRun: boolean;

  /** IDs of input files uploaded for this run. */
  inputAttachmentIds: string[];

  /** IDs of output files generated by this run. */
  outputAttachmentIds: string[];

  /** Error message if execution failed (empty string if no error). */
  errorMessage: string;

  /** Timestamp of creation. */
  createdAt: Date;

  /** Timestamp of last update. */
  updatedAt: Date;
};
