import { ToolCallEntry } from "./tool-call";
import { ToolResultEntry } from "./tool-result";

/**
 * Accumulated state of a chat stream.
 * Used as a mutable (or state-merged) object in the chat route to track the entire
 * response lifecycle, including generated text, reasoning, and tool interactions.
 *
 * @author Maruf Bepary
 */
export interface StreamState {
  /**
   * The complete accumulated text generated by the model so far.
   */
  fullText: string;

  /**
   * The complete accumulated reasoning/thought content generated by the model.
   */
  fullReasoning: string;

  /**
   * List of all tool calls initiated during this stream.
   */
  toolCalls: ToolCallEntry[];

  /**
   * List of all tool results received during this stream.
   */
  toolResults: ToolResultEntry[];
}
