import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Default SEO metadata shared across all routes.
 *
 * @author Maruf Bepary
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { TooltipProvider } from "@/components/ui/tooltip";
import { PopoverProvider } from "@/components/ui/popover";

/**
 * Root layout providing global fonts (Geist), CSS, and UI providers.
 * Establishes the HTML scaffold, theme context, and toast notification system for all routes.
 * Public route — no authentication required.
 *
 * @param children - Page content rendered within the layout.
 * @returns HTML document with font variables, tooltip/popover providers, and Sonner toaster.
 * @see AuthenticatedLayout for auth-protected routes.
 * @author Maruf Bepary
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <PopoverProvider>
            {children}
            <Toaster position="bottom-right" />
          </PopoverProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
