import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Default SEO metadata shared across all routes.
 *
 * @author Maruf Bepary
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { TooltipProvider } from "@/components/ui/tooltip";

/**
 * Root layout that wires global fonts, theming, and toast providers.
 *
 * @param children - Page content rendered within the layout shell.
 * @returns HTML scaffold shared across all routes.
 * @author Maruf Bepary
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          {children}
          <Toaster position="top-left" />
        </TooltipProvider>
      </body>
    </html>
  );
}
