"use client";

import { AlertCircle } from "lucide-react";

export interface HtmlViewProps {
  content: string;
}

/**
 * Renders HTML content in an isolated iframe with sandbox restrictions.
 * Used in ArtifactPanel to display HTML artifacts generated by AI.
 *
 * @param props.content - HTML string to render in the iframe.
 * @returns Iframe rendering the HTML content with restricted permissions.
 * @author Maruf Bepary
 */
export default function HtmlView({ content }: HtmlViewProps) {
  if (!content) {
    return (
      <div className="flex h-full flex-col items-center justify-center p-6 text-center text-muted-foreground gap-2">
        <AlertCircle className="h-8 w-8" />
        <p>No HTML content to display.</p>
      </div>
    );
  }

  return (
    <div className="flex h-full w-full bg-white relative">
      <iframe
        srcDoc={content}
        className="w-full h-full border-none"
        sandbox="allow-scripts allow-forms allow-same-origin allow-popups"
        title="HTML Preview"
      />
    </div>
  );
}
